
#when gettin info about all user profiles
GET http://localhost:8080/profiles
Content-Type: application/json

###
#when gettin info about all user profiles
GET http://localhost:8080/profiles
Content-Type: application/json
Authorization: Basic admin@lendahand.com password
###
GET http://localhost:8080/user/1
Content-Type: application/json

###
GET http://localhost:8080/user?username=admin@lendahand.com
Content-Type: application/json

###
#when gettin info adding a user
POST http://localhost:8080/signup
Content-Type: application/json

{
    "username" : "a string(email)",
    "password" : "a string",
    "firstname" : "string",
    "lastname" : "string",
    "contactNo" : "12345678"
}
###
DELETE  http://localhost:8080/user/delete/5
Content-Type: application/json
###
#get all listings
GET http://localhost:8080/listingpage
Content-Type: application/json

###

GET http://localhost:8080/listingpage?username=user@gmail.com
Content-Type: application/json

###
#get a listings based on its id
GET http://localhost:8080/listingpage/1
Content-Type: application/json
###
#put user id in the {id}
POST http://localhost:8080/listingpage/createlisting?userId=1
Content-Type: application/json

{
    "name" : "string",
    "des" : "string"
}

###
#put user id in the {id}
GET http://localhost:8080/user/applications?userId=1
Content-Type: application/json

###
#put application id in the {id}
GET http://localhost:8080/application/1
Content-Type: application/json

###
#put the corresponding ids in the {}
POST http://localhost:8080/listingpage/1/apply?userId=1
Content-Type: application/json

{
    "message" : "string"
}